- 
  name: Create AD User
  hosts: DC1.demo.netapp.com
  collections:
    - community.windows
  tasks:
  - name: Ensure user bob is present with address information
    community.windows.win_domain_user:
      name: bob
      firstname: Bob
      surname: Smith
      company: BobCo
      password: B0bP4ssw0rd
      state: present
      groups:
        - Domain Admins
      street: 123 4th St.
      city: Sometown
      state_province: IN
      postal_code: 12345
      country: US
      attributes:
        telephoneNumber: 555-123456
