- 
  name: Bad Permissions
  hosts: localhost
  collections:
    - netapp.ontap
    - community.windows
    - anisble.windows
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1_cluster1
    aggr: cluster1_01_SSD_1
    vol_name: photoshop
    cifs_user: dougd
  tasks:
  - name: Export Create
    na_ontap_export_policy:
      state: present
      name: photoshop_policy
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Export Policy Rule Create
    na_ontap_export_policy_rule:
      state: present
      name: photoshop_policy
      vserver: "{{ vserver }}"
      client_match: 0.0.0.0/0
      ro_rule: sys
      rw_rule: sys
      protocol: nfs
      super_user_security: sys
      anonymous_user_id: 65534
      allow_suid: false
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 1
      size_unit: gb
      policy: photoshop_policy
      junction_path: "/{{ vol_name }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
      volume_security_style: ntfs
  - name: CIFS Share Create
    na_ontap_cifs:
      state: present
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      path: "/{{ vol_name }}"
      share_name: "{{ vol_name }}"
      https: true
      validate_certs: false
  - name: Create User
    community.windows.win_domain_user:
      name: "{{ cifs_user }}"
      firstname: Doug
      surname: Dimmadome
      password: "{{ password }}"
      state: present
      domain_username: DEMO\Administrator
      domain_password: "{{ password }}"
      domain_server: dc1.demo.netapp.com@DEMO.NETAPP.COM
  - name: Add ACL
    ansible.windows.win_acl:
      user: "{{ cifs_user }}"
      path: \\192.168.0.131\photoshop
      type: allow
      rights: Read,ExecuteFile
